---

- name: Deploy PostgreSQL standalone | Pre-checks servers for playbook
  hosts: hosts_postgresql
  become: true
  become_method: sudo
  gather_facts: true
  tags: always
  any_errors_fatal: true
  environment: "{{ proxy_env | default({}) }}"

  pre_tasks:

    - name: System information
      ansible.builtin.debug:
        var: system_info
      vars:
        system_info:
          OS: "{{ ansible_distribution | default('N/A') }} {{ ansible_distribution_version | default('N/A') }}"
          Kernel: "{{ ansible_kernel | default('N/A') }}"
          CPU model: >-
            {{ ansible_processor[2] | default('N/A') }},
            count: {{ ansible_processor_count | default('N/A') }},
            cores: {{ ansible_processor_cores | default('N/A') }}
          Memory: "{{ (ansible_memtotal_mb / 1024) | round(2) if ansible_memtotal_mb is defined else 'N/A' }} GB"
          Disk space total: >-
            {{
              (ansible_mounts
                | map(attribute='size_total')
                | map('int')
                | sum / 1024 / 1024 / 1024
              )
              | round(2) if ansible_mounts is defined else 'N/A'
            }} GB
          Architecture: "{{ ansible_architecture | default('N/A') }}"
          Virtualization type: "{{ ansible_virtualization_type | default('N/A') }}"
          Product name: "{{ ansible_product_name | default('N/A') }}"
      tags: always

  tasks:
   - name: Get ansible_host IP
    debug:
      msg: "IP Address (ansible_host): {{ ansible_host }}"

  - name: Get default IPv4 IP address
    debug:
      msg: "Default IPv4 IP Address: {{ ansible_default_ipv4.address }}"